#!/usr/bin/env python3
"""
URDF-based Kinematics Bridge between Leader and Follower Robots
Created by Sandor Burian with the help of Copilot (Claude Sonnet 4)

This module transforms the end-effector positions from the Leader robot's
coordinate system to the Follower robot's coordinate system,
applying scaling, rotation, translation, and safety limits,
using URDF files for kinematics.
"""

import numpy as np
import ikpy.chain
from dataclasses import dataclass
from typing import List, Optional

@dataclass
class MappingConfig:
    scale_factor: float = 1.8
    offset_x: float = 0.0
    offset_y: float = 0.0
    offset_z: float = 0.0
    rotation_z: float = 0.0
    safety_factor: float = 0.9          #(usually 90-95%)
    inner_deadzone_factor: float = 0.15 #(usually 10-15% of arm length)
    min_z: float = 0.05
    max_z: float = 0.90
    max_radius: float = 0.60
    min_radius: float = 0.15
    name: str = "Arm B" 

class URDFBasedKinematicBridge:
    def __init__(self, config: Optional[MappingConfig] = None, leader_urdf="../demo/SO100/URDF/so100.urdf", follower_urdf="../demo/AR4/URDF/ar4.urdf"):
        self.config = config
        self.limit_reached = False
        
        # Loading kinematics for both robot
        try:
            self.leader_chain = ikpy.chain.Chain.from_urdf_file(leader_urdf, base_elements=["base"])
            self.follower_chain = ikpy.chain.Chain.from_urdf_file(follower_urdf, base_elements=["base_link"])
            print("URDF loaded successfully!")
        except Exception as e:
            print(f"Error loading URDF: {e}")
            self.follower_chain = None
        
        if config is None:
            self.config = self._auto_calculate_config()
        else:
            self.config = config

        self.limit_reached = False

    def _auto_calculate_config(self):
        """Scale the robot based on paramters"""
        print("Callibrating...")
        
        l_reach = self._calculate_reach(self.leader_chain)
        f_reach = self._calculate_reach(self.follower_chain)
        arm_name = self.follower_chain.name if self.follower_chain.name else "Follower Robot"
        
        print(f" - Leader Reach:\t{l_reach:.3f} m")
        print(f" - Follower Reach:\t{f_reach:.3f} m")
        
        # Scale calculation (with safety factor to avoid overextension)
        auto_scale = (f_reach / l_reach) * self.config.safety_factor
        
        # Maximum radius
        max_rad = f_reach * self.config.safety_factor
        
        #  Inner dead zone estimation
        min_rad = f_reach * self.config.inner_deadzone_factor

        min_z_safety = 0.02 # 2 cm safety margin
        
        print(f" -> Scale:\t{auto_scale:.2f}x")
        
        return MappingConfig(
            scale_factor=auto_scale,
            max_radius=max_rad,
            min_radius=min_rad, # 0.05 in angle mode
            min_z=min_z_safety,
            max_z=f_reach * 0.95,
            name=arm_name
        )
    
    def transform(self, leader_pos: List[float]) -> List[float]:
        self.limit_reached = False
        lx, ly, lz = leader_pos
        c = self.config
        
        # 1. Scaling and Translation (Mathematical transformation)
        x = lx * c.scale_factor
        y = ly * c.scale_factor
        z = lz * c.scale_factor
        
        # Rotation
        if c.rotation_z != 0:
            rad = np.radians(c.rotation_z)
            x_new = x * np.cos(rad) - y * np.sin(rad)
            y_new = x * np.sin(rad) + y * np.cos(rad)
            x, y = x_new, y_new

        x += c.offset_x
        y += c.offset_y
        z += c.offset_z
        
        # 2. CYLINDRICAL WORKSPACE VALIDATION (Safety Limits)
        radius = np.sqrt(x**2 + y**2)
        
        # Check workspace boundaries
        if (z < c.min_z or z > c.max_z or radius > c.max_radius or radius < c.min_radius):
            self.limit_reached = True
            
            # Clamp to safe boundaries # generated by Google Gemini Pro
            z = max(c.min_z, min(c.max_z, z))
            if radius > c.max_radius:
                scale_factor = c.max_radius / radius
                x *= scale_factor
                y *= scale_factor
            # inner boundaries
            elif radius < c.min_radius:
                if radius > 0.001: # If not 0, push proportionally outward
                    scale_factor = c.min_radius / radius
                    x *= scale_factor
                    y *= scale_factor
                else:
                    # IF THE RADIUS IS 0 (OR VERY SMALL):
                    x = c.min_radius
                    y = 0.0
        
        # 3. IK SOLVER VALIDATION 
        if self.follower_chain:
            target_vector = [x, y, z]
            
            inverse_angles   = self.follower_chain.inverse_kinematics(target_vector)
            real_reached_pos = self.follower_chain.forward_kinematics(inverse_angles)[:3, 3]
            
            # Calculate the error (Distance from the target)
            distance_error = np.linalg.norm(real_reached_pos - target_vector)
            
            # If the error is greater than 5 cm (0.05), the point is UNREACHABLE
            if distance_error > 0.05:
                self.limit_reached = True
                # Return the "closest reachable" point
                x, y, z = real_reached_pos 
        
        return [x, y, z]
    
    def update_config(self, **kwargs):
        """Modify settings at runtime (e.g., from GUI or config file)"""
        for key, value in kwargs.items():
            if hasattr(self.config, key):
                setattr(self.config, key, value)